# Header info
name: "Danny"
bio: "Software Engineer"

# Links
Twitter: "https://twitter.com/@DNYFZR"
Medium: "https://medium.com/@DNYFZR"
GitHub: "https://github.com/DNYFZR"
Website: "https://dnyfzr.github.io/"
