# Header info
name: "Danny"
info: "Software Developer | Data Engineer | Open Source Advocate | Tech Blogger"

# Links
Github: "https://github.com/DNYFZR"
Twitter: "https://twitter.com/@DNYFZR"
Medium: "https://medium.com/@DNYFZR"
TennisApp: "https://tennis.streamlitapp.com/"
