# Header info
name: "Danny"
bio: "Software Developer | Data Engineer | Tech Blogger"

# Links
Github: "https://github.com/DNYFZR"
Twitter: "https://twitter.com/@DNYFZR"
Medium: "https://medium.com/@DNYFZR"
Tennis App: "https://tennis.streamlitapp.com/"
